/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import Clases.Exportacion;
import Clases.ExportacionCargaPesada;
import Clases.ExportacionCargaSuelta;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cesc
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private java.util.ArrayList<Exportacion> listaExportaciones = new java.util.ArrayList<>();
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        cargarDatos();
        actualizarTabla();
    }
    
    private void guardarDatos() {
        // Guarda la lista completa de exportaciones en el archivo Exportaciones.dat
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Exportaciones.dat"))) {
            oos.writeObject(this.listaExportaciones);
            System.out.println("Datos guardados correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos en el archivo.", "Error de Archivo", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarDatos() {
        // Carga la lista de exportaciones desde el archivo Exportaciones.dat
        File archivo = new File("Exportaciones.dat");
        if (archivo.exists()) {
            try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(archivo))) {
                // Lee el objeto del archivo y lo convierte de nuevo a una ArrayList
                this.listaExportaciones = (ArrayList<Exportacion>) ois.readObject();
                System.out.println("Datos cargados correctamente.");
            } catch (IOException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar los datos desde el archivo.", "Error de Archivo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNueva = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExportaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNueva.setText("Nueva Exportación");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar Selección");

        btnEliminar.setText("Eliminar Selección");

        tblExportaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblExportaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btnNueva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(280, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNueva)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(86, 86, 86)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        //    El 'this' se refiere a la VentanaPrincipal (su padre).
        //    El 'true' lo hace "modal" (bloquea la ventana de atrás hasta que este se cierre).
        DialogoNuevaExportacion dialogo = new DialogoNuevaExportacion(this, true);
        dialogo.setVisible(true);
        
        Exportacion exportacionCreada = dialogo.getNuevaExportacion();

        if (exportacionCreada != null) {
            this.listaExportaciones.add(exportacionCreada);
            this.actualizarTabla();

            // Llama al método para guardar la lista actualizada en el archivo
            this.guardarDatos();
        }
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void actualizarTabla() {
        // Define los nombres de las columnas para la tabla
        String[] columnas = {"ID Cliente", "Nombre", "Fecha", "Zona Envío", "Servicio", "Costo Total"};

        // Crea un modelo de tabla no editable
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        // Recorre la lista de exportaciones
        for (Exportacion exp : this.listaExportaciones) {
            // Crea una fila con los datos de cada objeto
            Object[] fila = {
                exp.getIdCliente(),
                exp.getNombreCompleto(),
                exp.getFechaExportacionFormateada(),
                exp.getZonaEnvio(),
                exp.getTipoServicio(),
                String.format("$%.2f", exp.getCostoTotal()) // Formatea el costo
            };
            // Agrega la fila al modelo
            modeloTabla.addRow(fila);
        }

        // Asigna el modelo recién creado a nuestra JTable
        this.tblExportaciones.setModel(modeloTabla);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNueva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExportaciones;
    // End of variables declaration//GEN-END:variables
}
